import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const places = [
  // RESTAURANTS
  {
    name: "ส้มตำลาว หัวหิน",
    slug: "somtam-lao-hua-hin",
    type: "RESTAURANT",
    status: "published",
    featured: true,
    description: "ส้มตำรสจัด สไตล์ลาว ต้มแซบ ไก่ย่าง ข้าวเหนียว บรรยากาศร้านไทย ราคาประชาชน",
    cuisine: "somtam",
    priceRange: "cheap",
    area: "hua-hin",
    address: "ถ.เพชรเกษม หัวหิน 77110",
    phone: "032-515-111",
    rating: 4.7,
    reviewCount: 843,
    openingHours: "10:00–22:00",
    tags: "somtam,isaan,papaya-salad,grilled-chicken,sticky-rice",
    coverImage: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&q=80",
    seoTitle: "ส้มตำลาว หัวหิน — ร้านส้มตำรีวิวดี คนชมเยอะ",
    seoDesc: "ส้มตำรสจัดสไตล์ลาว ไก่ย่างหอม ข้าวเหนียวนุ่ม ใจกลางหัวหิน ราคาย่อมเยา",
  },
  {
    name: "ส้มตำแซ่บ เขาตะเกียบ",
    slug: "somtam-saeb-khao-takiab",
    type: "RESTAURANT",
    status: "published",
    featured: false,
    description: "ส้มตำรสดั้งเดิม ปูปลาร้า พร้อมหมูย่าง ไก่ย่าง วิวทะเลริมหาดเขาตะเกียบ",
    cuisine: "somtam",
    priceRange: "cheap",
    area: "khao-takiab",
    address: "ริมหาดเขาตะเกียบ หัวหิน",
    phone: "032-516-222",
    rating: 4.5,
    reviewCount: 512,
    openingHours: "09:00–21:00",
    tags: "somtam,isaan,sea-view,affordable",
    coverImage: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80",
    seoTitle: "ส้มตำแซ่บ เขาตะเกียบ — ส้มตำวิวทะเล",
    seoDesc: "ส้มตำรสแซ่บ วิวทะเลสวย ริมหาดเขาตะเกียบ ราคาถูก",
  },
  {
    name: "Baan Itsara Indian Restaurant",
    slug: "baan-itsara-indian-restaurant",
    type: "RESTAURANT",
    status: "published",
    featured: true,
    description: "Authentic Indian cuisine in the heart of Hua Hin. Known for rich curries, tandoori dishes, and warm hospitality.",
    cuisine: "indian",
    priceRange: "moderate",
    area: "hua-hin",
    address: "Phetkasem Rd, Hua Hin 77110",
    phone: "032-512-000",
    rating: 4.6,
    reviewCount: 312,
    openingHours: "11:00–22:00",
    tags: "indian,curry,tandoori,naan,vegetarian",
    coverImage: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80",
    seoTitle: "Best Indian Restaurant in Hua Hin — Baan Itsara",
    seoDesc: "Authentic Indian food in Hua Hin. Rich curries, tandoori, and fresh naan. Open daily 11am–10pm.",
  },
  {
    name: "The Azure Blue Grill",
    slug: "azure-blue-grill",
    type: "RESTAURANT",
    status: "published",
    featured: true,
    description: "A luxurious seaside restaurant offering the finest Thai seafood with breathtaking ocean views.",
    cuisine: "thai-seafood",
    priceRange: "expensive",
    area: "khao-takiab",
    address: "Khao Takiab Coast, Hua Hin",
    phone: "032-520-111",
    rating: 4.9,
    reviewCount: 528,
    openingHours: "17:00–23:00",
    tags: "seafood,beachfront,fine-dining,sunset",
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    seoTitle: "Azure Blue Grill — Beachfront Seafood Restaurant Hua Hin",
    seoDesc: "Fine dining seafood on Khao Takiab beach. Book your sunset table today.",
  },
  {
    name: "Yume Sushi Hub",
    slug: "yume-sushi-hub",
    type: "RESTAURANT",
    status: "published",
    featured: false,
    description: "Premium omakase sushi experience with the freshest fish flown in daily from Tokyo's Tsukiji market.",
    cuisine: "japanese",
    priceRange: "luxury",
    area: "hua-hin",
    address: "BluPort District, Hua Hin",
    phone: "032-521-888",
    rating: 5.0,
    reviewCount: 156,
    openingHours: "18:00–23:00",
    tags: "sushi,japanese,omakase,fine-dining",
    coverImage: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80",
    seoTitle: "Yume Sushi Hub — Premium Japanese Omakase Hua Hin",
    seoDesc: "Experience authentic omakase sushi in Hua Hin. Fresh fish, expert chefs, intimate dining.",
  },
  {
    name: "La Terrazza Italian Bistro",
    slug: "la-terrazza-italian-bistro",
    type: "RESTAURANT",
    status: "published",
    featured: false,
    description: "Authentic Italian cuisine with fresh handmade pasta, wood-fired pizza, and an extensive wine list.",
    cuisine: "italian",
    priceRange: "moderate",
    area: "hua-hin",
    address: "Soi 94 Food District, Hua Hin",
    phone: "032-531-200",
    rating: 4.7,
    reviewCount: 234,
    openingHours: "12:00–22:30",
    tags: "italian,pasta,pizza,wine",
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    seoTitle: "La Terrazza — Authentic Italian Restaurant Hua Hin",
    seoDesc: "Fresh pasta, wood-fired pizza and fine Italian wines in Soi 94 Food District.",
  },
  {
    name: "Seaside Beach BBQ",
    slug: "seaside-beach-bbq",
    type: "RESTAURANT",
    status: "published",
    featured: false,
    description: "A festive beachside BBQ with fire dancers, live music, and an unforgettable tropical spread.",
    cuisine: "bbq",
    priceRange: "moderate",
    area: "cha-am",
    address: "Cha-Am Beach, Phetchaburi",
    phone: "032-433-100",
    rating: 4.5,
    reviewCount: 412,
    openingHours: "17:00–24:00",
    tags: "bbq,beach,grilled,seafood,live-music",
    coverImage: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    seoTitle: "Seaside Beach BBQ — Cha-Am Beach Restaurant",
    seoDesc: "Enjoy fresh BBQ on Cha-Am beach with live music and fire dancers every evening.",
  },
  // HOTELS
  {
    name: "Anantara Hua Hin Resort",
    slug: "anantara-hua-hin-resort",
    type: "HOTEL",
    status: "published",
    featured: true,
    description: "A luxurious 5-star beachfront resort surrounded by tropical gardens and the Gulf of Thailand.",
    hotelType: "resort",
    starRating: 5,
    priceRange: "luxury",
    area: "hua-hin",
    address: "43/1 Phetkasem Beach Rd, Hua Hin",
    phone: "032-520-250",
    website: "https://www.anantara.com/en/hua-hin",
    rating: 4.8,
    reviewCount: 1240,
    tags: "resort,luxury,beachfront,pool,spa",
    coverImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    seoTitle: "Anantara Hua Hin Resort — 5-Star Luxury Beachfront Hotel",
    seoDesc: "Experience ultimate luxury at Anantara Hua Hin. Private beach, infinity pool, world-class spa.",
  },
  {
    name: "The Barai Hyatt Regency",
    slug: "barai-hyatt-regency-hua-hin",
    type: "HOTEL",
    status: "published",
    featured: true,
    description: "Exclusive wellness-focused resort where ancient Thai healing traditions meet modern luxury.",
    hotelType: "resort",
    starRating: 5,
    priceRange: "luxury",
    area: "hua-hin",
    address: "91 Hua Hin-Khao Takiab Rd, Hua Hin",
    phone: "032-521-234",
    rating: 4.9,
    reviewCount: 890,
    tags: "resort,spa,wellness,luxury,beachfront",
    coverImage: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    seoTitle: "The Barai Hyatt — Luxury Spa Resort Hua Hin",
    seoDesc: "Award-winning wellness resort in Hua Hin. Experience ancient Thai healing and modern luxury.",
  },
  // ATTRACTIONS
  {
    name: "Hua Hin Night Market",
    slug: "hua-hin-night-market",
    type: "ATTRACTION",
    status: "published",
    featured: true,
    description: "The iconic Hua Hin Night Market is a must-visit for fresh seafood, street food, and local souvenirs.",
    category: "market",
    area: "hua-hin",
    address: "Dechanuchit Rd, Hua Hin",
    rating: 4.6,
    reviewCount: 2100,
    openingHours: "17:00–23:00",
    tags: "market,street-food,seafood,shopping,nightlife",
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    seoTitle: "Hua Hin Night Market — Best Street Food in Hua Hin",
    seoDesc: "Experience the vibrant Hua Hin Night Market with fresh seafood, street food, and local crafts.",
  },
  {
    name: "Khao Takiab Temple (Monkey Mountain)",
    slug: "khao-takiab-temple",
    type: "ATTRACTION",
    status: "published",
    featured: false,
    description: "A hilltop temple with panoramic sea views and friendly resident monkeys. A Hua Hin icon.",
    category: "temple",
    area: "khao-takiab",
    address: "Khao Takiab Hill, Hua Hin",
    rating: 4.4,
    reviewCount: 1567,
    openingHours: "06:00–18:00",
    tags: "temple,monkeys,viewpoint,culture,family",
    coverImage: "https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?w=800&q=80",
    seoTitle: "Khao Takiab Temple Hua Hin — Monkey Mountain Guide",
    seoDesc: "Visit the iconic Khao Takiab temple for panoramic sea views and friendly monkeys in Hua Hin.",
  },
  {
    name: "Pranburi Forest Park & Mangroves",
    slug: "pranburi-forest-park",
    type: "ATTRACTION",
    status: "published",
    featured: false,
    description: "Explore the pristine mangrove forests of Pranburi, one of the best-preserved coastal parks near Hua Hin.",
    category: "nature",
    area: "pranburi",
    address: "Pranburi Forest Park, Prachuap Khiri Khan",
    rating: 4.7,
    reviewCount: 634,
    openingHours: "08:00–17:00",
    tags: "nature,mangrove,birds,cycling,eco-tourism",
    coverImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    seoTitle: "Pranburi Forest Park — Mangrove & Nature Tour near Hua Hin",
    seoDesc: "Discover Pranburi's pristine mangrove forests just 30 minutes from Hua Hin.",
  },
];

async function main() {
  console.log("Seeding database...");

  for (const place of places) {
    await prisma.place.upsert({
      where: { slug: place.slug },
      update: place,
      create: place,
    });
  }

  console.log(`✓ Seeded ${places.length} places`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
