export const RE_CITIES = [
  {
    slug:      "real-estate-hua-hin",
    city:      "Hua Hin",
    cityTh:    "หัวหิน",
    tagline:   "Royal beach town, premium lifestyle",
    taglineTh: "ชายหาดหลวง ที่พักอาศัยระดับพรีเมียม",
    img:       "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&q=80",
  },
  {
    slug:      "real-estate-bangkok",
    city:      "Bangkok",
    cityTh:    "กรุงเทพมหานคร",
    tagline:   "Business hub, 4–7% rental yield",
    taglineTh: "ศูนย์กลางธุรกิจ Yield 4–7%",
    img:       "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400&q=80",
  },
  {
    slug:      "real-estate-chonburi",
    city:      "Chonburi",
    cityTh:    "ชลบุรี",
    tagline:   "EEC Hub, strong infrastructure",
    taglineTh: "EEC Hub โครงสร้างพื้นฐานแน่น",
    img:       "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400&q=80",
  },
  {
    slug:      "real-estate-phuket",
    city:      "Phuket",
    cityTh:    "ภูเก็ต",
    tagline:   "Luxury villas, 8–10% yield",
    taglineTh: "วิลล่าหรู Yield 8–10%",
    img:       "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=400&q=80",
  },
  {
    slug:      "real-estate-nonthaburi",
    city:      "Nonthaburi",
    cityTh:    "นนทบุรี",
    tagline:   "BTS/MRT access, affordable price",
    taglineTh: "ทำเลติด BTS/MRT ราคาย่อมเยา",
    img:       "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=400&q=80",
  },
  {
    slug:      "real-estate-cha-am",
    city:      "Cha-Am",
    cityTh:    "ชะอำ",
    tagline:   "Great value, high growth potential",
    taglineTh: "ราคาดี ศักยภาพเติบโตสูง",
    img:       "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
  },
  {
    slug:      "real-estate-pranburi",
    city:      "Pranburi",
    cityTh:    "ปราณบุรี",
    tagline:   "Nature, privacy & quiet beaches",
    taglineTh: "ธรรมชาติ ความเป็นส่วนตัวสูง",
    img:       "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&q=80",
  },
  {
    slug:      "real-estate-koh-samui",
    city:      "Koh Samui",
    cityTh:    "เกาะสมุย",
    tagline:   "Infinity pool villas on the island",
    taglineTh: "วิลล่า infinity pool บนเกาะ",
    img:       "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&q=80",
  },
  {
    slug:      "real-estate-pattaya",
    city:      "Pattaya",
    cityTh:    "พัทยา",
    tagline:   "Affordable condos near Bangkok",
    taglineTh: "คอนโดราคาเข้าถึงได้ ใกล้กรุงเทพฯ",
    img:       "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80",
  },
  {
    slug:      "real-estate-samut-prakan",
    city:      "Samut Prakan",
    cityTh:    "สมุทรปราการ",
    tagline:   "Gateway to Suvarnabhumi Airport",
    taglineTh: "ประตูสู่สนามบินสุวรรณภูมิ",
    img:       "https://images.unsplash.com/photo-1559941727-6fb446e7e8ae?w=400&q=80",
  },
  {
    slug:      "real-estate-chiang-mai",
    city:      "Chiang Mai",
    cityTh:    "เชียงใหม่",
    tagline:   "Top pick for digital nomads & expats",
    taglineTh: "Digital nomad & ผู้เกษียณ Expat",
    img:       "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=400&q=80",
  },
  {
    slug:      "real-estate-prachuap",
    city:      "Prachuap Khiri Khan",
    cityTh:    "ประจวบคีรีขันธ์",
    tagline:   "Gulf Coast nature, peaceful living",
    taglineTh: "ธรรมชาติอ่าวไทย บรรยากาศเงียบสงบ",
    img:       "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=400&q=80",
  },
  {
    slug:      "real-estate-rayong",
    city:      "Rayong",
    cityTh:    "ระยอง",
    tagline:   "EEC Eastern Seaboard corridor",
    taglineTh: "EEC แนวชายฝั่งตะวันออก",
    img:       "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=400&q=80",
  },
  {
    slug:      "real-estate-pathum-thani",
    city:      "Pathum Thani",
    cityTh:    "ปทุมธานี",
    tagline:   "New housing estates, accessible price",
    taglineTh: "บ้านจัดสรรใหม่ ราคาเข้าถึงได้",
    img:       "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&q=80",
  },
  {
    slug:      "real-estate-surat-thani",
    city:      "Surat Thani",
    cityTh:    "สุราษฎร์ธานี",
    tagline:   "Gateway to Samui & the South",
    taglineTh: "ประตูสู่สมุย & ทะเลใต้",
    img:       "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80",
  },
  {
    slug:      "real-estate-krabi",
    city:      "Krabi",
    cityTh:    "กระบี่",
    tagline:   "Islands, beaches & limestone cliffs",
    taglineTh: "เกาะ หาด หน้าผา ธรรมชาติสวย",
    img:       "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?w=400&q=80",
  },
  {
    slug:      "real-estate-phang-nga",
    city:      "Phang Nga",
    cityTh:    "พังงา",
    tagline:   "Phang Nga Bay, world-class scenery",
    taglineTh: "อ่าวพังงา วิวสวยระดับโลก",
    img:       "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=400&q=80",
  },
] as const;
